# Generated by Django 4.0.4 on 2022-05-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='descripcion',
            field=models.CharField(max_length=500, null=True, verbose_name='descripcion'),
        ),
    ]
