# Generated by Django 4.0.4 on 2022-05-12 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0003_author_libro_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='libreria.author'),
        ),
    ]
