# Generated by Django 4.0.4 on 2022-05-12 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0004_alter_libro_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='author',
        ),
    ]
